package com.example.onlinemarketplace.model;

public enum CategoryType {
    PHONES_AND_GADGETS,
    APPLIANCES,
    TV_AUDIO_VIDEO,
    COMPUTERS,
    FURNITURE,
    BEAUTY_HEALTH,
    CHILDREN_PRODUCTS,
    PHARMACY,
    CONSTRUCTION_REPAIR,
    SPORT,
    TOURISM,
    LEISURE_BOOKS,
    AUTOMOTIVE_PRODUCTS,
    DECORATION,
    ACCESSORIES,
    CLOTHES,
    SHOES,
    HOUSEHOLD_COTTAGE_GOODS,
    PET_PRODUCTS,
    GIFTS_GOODS_FOR_HOLIDAYS,
    OFFICE_SUPPLIES
}
